services:
  frontend:
    image: ${frontend}
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      caddy: a-bit-of-it.com, a-bit-of-it.dk
      caddy.handle: /*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

  api:
    image: ${api}
    restart: unless-stopped
    networks:
      - proxy-net
    env_file:
      - .env
    labels:
      caddy: a-bit-of-it.com, a-bit-of-it.dk
      caddy.handle: /api/*
      caddy.handle.reverse_proxy: "{{upstreams 8080}}"

networks:
  proxy-net:
    external: true