services:
  frontend:
    build:
      context: ./Frontend
    restart: unless-stopped

  api:
    build:
      context: ./Api
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
