name: Build and Push Images on Tag
on:
  push:
    tags: ['*']

jobs:
  build-web:
    uses: a-bit-of-it/workflows/.github/workflows/build-and-push.yml@v1
    with:
      component: frontend
    secrets: inherit

  build-api:
    uses: a-bit-of-it/workflows/.github/workflows/build-and-push.yml@v1
    with:
      component: api
    secrets: inherit